apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-mongo-sink-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: iot.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-mongo-sink-svc
                port:
                  number: 8083
