resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: kafka-mongo-sink
      scrape_logs: "true"
    includeSelectors: true

configMapGenerator:
  - name: kafka-connect-jmx-config
    files:
      - jmx-config.yaml