apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          command:
            - bash
            - -c
            - unset SCHEMA_REGISTRY_PORT; /etc/confluent/docker/run
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-svc:9092
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-svc:9092
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS
              value: GET,POST,PUT,OPTIONS
            - name: SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN
              value: "*"
          readinessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5