apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-control-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: command-control-service
          image: ihorlapka/iot-command-control-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          volumeMounts:
            - name: app-config
              mountPath: /config/application.yaml
              subPath: application.yaml
          env:
            - name: JAVA_OPTS
              value: "-Xms350m -Xmx350m -XX:+UseG1GC -XX:ParallelGCThreads=2 -XX:ConcGCThreads=1 -XX:MaxDirectMemorySize=64m -Xlog:gc*,gc+heap=info"
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: REGISTRY_BASE_URL
              value: "http://registry-svc-dev:8080"
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /iot-commands/actuator/health/readiness
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /iot-commands/actuator/health/liveness
              port: 8087
            initialDelaySeconds: 80
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: dockercred
      volumes:
        - name: app-config
          configMap:
            name: command-control-service-config