apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: iot.local
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /prometheus(/|$)(.*)
            backend:
              service:
                name: prometheus-svc
                port:
                  number: 9090
