resources:
  - statefulSet.yaml
  - service.yaml
  - ingress.yaml
  - cm.yaml
  - serviceAccount.yaml
  - clusterRole.yaml
  - clusterRoleBinding.yaml

labels:
  - pairs:
      app: prometheus
    includeSelectors: true