apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: command-control-service-ingress
spec:
  rules:
    - host: iot.local
      http:
        paths:
          - path: /iot-commands
            pathType: Prefix
            backend:
              service:
                name: command-control-service-svc-dev
                port:
                  number: 8087