apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
spec:
  rules:
    - host: iot.local
      http:
        paths:
          - path: /iot-registry
            pathType: Prefix
            backend:
              service:
                name: registry-svc-dev
                port:
                  number: 8080