resources:
  - ../../base
  - ingress.yaml

nameSuffix:
  -dev

configMapGenerator:
  - name: registry-config
    files:
      - application.yaml

images:
  - name: ihorlapka/iot-registry-service
    newTag: "1"