apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

nameSuffix: -dev

configMapGenerator:
- files:
  - application.yaml
  name: registry-config

images:
- name: ihorlapka/iot-registry-service
  newTag: "107"
