apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetries-persister-ingress
spec:
  rules:
    - host: iot.local
      http:
        paths:
          - path: /telemetries-persister
            pathType: Prefix
            backend:
              service:
                name: telemetries-persister-svc-dev
                port:
                  number: 8082