resources:
  - ../../base
  - ingress.yaml

nameSuffix:
  -dev

configMapGenerator:
  - name: telemetries-persister-config
    files:
      - application.yaml

images:
  - name: ihorlapka/iot-telemetry-ingestion-service
    newTag: "1"