apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

nameSuffix: -dev

configMapGenerator:
- files:
  - application.yaml
  name: telemetries-persister-config

images:
- name: ihorlapka/iot-telemetry-ingestion-service
  newTag: "27"
