apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-events-processor
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/tep/actuator/prometheus"
    spec:
      containers:
        - name: telemetry-events-processor
          image: ihorlapka/iot-telemetry-event-processor
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: app-config
              mountPath: /config/application.yaml
              subPath: application.yaml
          env:
            - name: JAVA_OPTS
              value: "-Xms700m -Xmx700m -XX:+UseG1GC -XX:ParallelGCThreads=2 -XX:ConcGCThreads=1 -XX:MaxDirectMemorySize=128m -Xlog:gc*,gc+heap=info"
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            limits:
              memory: 1Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /tep/actuator/health/readiness
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /tep/actuator/health/liveness
              port: 8085
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: dockercred
      volumes:
        - name: app-config
          configMap:
            name: telemetry-events-processor-config