apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix:
  -dev

configMapGenerator:
  - name: telemetry-events-processor-config
    files:
      - application.yaml

images:
  - name: ihorlapka/iot-telemetry-event-processor
    newTag: "8"