apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -dev

configMapGenerator:
- files:
  - application.yaml
  name: telemetry-events-processor-config

images:
- name: ihorlapka/iot-telemetry-event-processor
  newTag: "16"
