apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: simulator
          image: ihorlapka/iot-simulator:latest
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: app-config
              mountPath: /config/application.yaml
              subPath: application.yaml
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m -XX:+UseG1GC"
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: USERNAME
              value: "simulator_app"
            - name: PASSWORD
              value: "simulator_123"
            - name: REGISTRY_BASE_URL
              value: "http://registry-svc-dev:8080"
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 250m
          readinessProbe:
            httpGet:
              path: /iot-device-connector/actuator/health/readiness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /iot-device-connector/actuator/health/liveness
              port: 8086
            initialDelaySeconds: 80
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: dockercred
      volumes:
        - name: app-config
          configMap:
            name: simulator-config