apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: simulator-dev
      scrape_logs: "true"
    includeSelectors: true

nameSuffix:
  -dev

configMapGenerator:
  - name: simulator-config
    files:
      - application.yaml

images:
  - name: ihorlapka/iot-simulator
    newTag: "1"