resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: simulator-dev
      scrape_logs: "true"
    includeSelectors: true

nameSuffix:
  -dev

configMapGenerator:
  - name: simulator-config
    files:
      - application.yaml