apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-visualisation-ingress
spec:
  rules:
    - host: iot.local
      http:
        paths:
          - path: /avs
            pathType: Prefix
            backend:
              service:
                name: analytics-visualisation-svc-dev
                port:
                  number: 8084