apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

nameSuffix:
  -dev

configMapGenerator:
  - name: analytics-visualisation-config
    files:
      - application.yaml

images:
  - name: ihorlapka/iot-analytics-visualisation-service
    newTag: "1"